### ISSUE TITLE
Create New Opposition Value looks unclickable

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories#78]
Given the user has opened the Character Value Comparison tool
And the user has created a new value web
When the user clicks Add Value

**Expected Result**
Then the Add Value drop down menu should show Create New Opposition Value selectable options in full black.

**Actual Result**
Then the Add Value drop down menu shows [Create New Opposition Value] as faded grey as if it was not selectable.

![image](https://user-images.githubusercontent.com/61167122/100524773-1ac6ba00-3178-11eb-8c6e-92e4dea019dd.png)

**Comment by b-camphart** [comment]
@ryanreso1993 please verify with new release

**Comment by ryanreso1993** [comment]
Bug fixed, the choices are much more intuitive and available
